# Generated by Django 2.2.2 on 2019-06-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("example_app", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("pending", "Approved")],
                default="pending",
                max_length=1000,
            ),
        )
    ]
