# Generated by Django 4.2 on 2025-09-12 02:24

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("example_app", "0002_image_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("products", 0),
                    ("images", 1),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "example_app.blocks.ProductBlock",
                        (),
                        {"target_model": "example_app.product"},
                    ),
                    1: (
                        "example_app.blocks.ImageBlock",
                        (),
                        {"target_model": "example_app.image"},
                    ),
                },
            ),
        ),
    ]
