name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tests-and-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            wagtail-version: "6.3"
            django-version: "4.2"
          - python-version: "3.11"
            wagtail-version: "7.0"
            django-version: "5.0"
          - python-version: "3.12"
            wagtail-version: "7.1"
            django-version: "5.1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the django & wagtail versions specified in the matrix
          pip install "Django~=${{ matrix.django-version }}.0"
          pip install wagtail==${{ matrix.wagtail-version }}
          pip install .[testing,dev]

      - name: Check Python linting (Ruff)
        run: ruff check --output-format=github

      - name: Check Python formatting (Ruff)
        run: ruff format --check

      - name: Run tests
        run: python runtests.py
